//! The sole terminal-emulation boundary for Bastion.
//!
//! Consumers receive a stable, renderer-neutral cell snapshot.  This keeps
//! Alacritty types out of the daemon protocol and lets the dashboard evolve
//! independently from the engine that interprets PTY escape sequences.

use alacritty_terminal::{
    event::{Event, EventListener},
    grid::{Dimensions, Scroll},
    term::{Config, Term, cell::Flags},
    vte::ansi::{CursorShape as AlacrittyCursorShape, Processor, StdSyncHandler},
};
use serde::{Deserialize, Serialize};
use std::sync::{Arc, Mutex};

#[derive(Clone, Copy)]
struct Size {
    rows: usize,
    columns: usize,
}

impl Dimensions for Size {
    fn total_lines(&self) -> usize {
        self.rows
    }

    fn screen_lines(&self) -> usize {
        self.rows
    }

    fn columns(&self) -> usize {
        self.columns
    }
}

/// A renderer-neutral terminal cell. Color mapping will be added alongside the
/// dashboard renderer migration; attributes already preserve the current
/// daemon snapshot contract.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum CellColor {
    DefaultForeground,
    DefaultBackground,
    Named(u16),
    Indexed(u8),
    Rgb { r: u8, g: u8, b: u8 },
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct Cell {
    pub text: String,
    pub wide_continuation: bool,
    pub bold: bool,
    pub italic: bool,
    pub underline: bool,
    pub inverse: bool,
    pub foreground: CellColor,
    pub background: CellColor,
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct Snapshot {
    pub rows: u16,
    pub cols: u16,
    pub output: String,
    pub cells: Vec<Vec<Cell>>,
    /// The live cursor is omitted while the viewport is in scrollback.
    pub cursor: Option<TerminalCursor>,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct TerminalCursor {
    pub row: u16,
    pub column: u16,
    pub shape: CursorShape,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum CursorShape {
    Block,
    Underline,
    Beam,
    HollowBlock,
}

/// The mouse protocol currently requested by the terminal application.
/// Bastion uses this to forward Android touch-scroll gestures faithfully.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum MouseProtocol {
    X10,
    Sgr,
}

/// Stateful Alacritty parser and grid for one PTY pane.
pub struct Terminal {
    size: Size,
    parser: Processor<StdSyncHandler>,
    term: Term<ReplySink>,
    replies: ReplySink,
}

impl Terminal {
    pub fn new(rows: u16, cols: u16) -> Self {
        let size = normalized_size(rows, cols);
        let replies = ReplySink::default();
        Self {
            size,
            parser: Processor::new(),
            term: Term::new(Config::default(), &size, replies.clone()),
            replies,
        }
    }

    pub fn process(&mut self, bytes: &[u8]) {
        self.parser.advance(&mut self.term, bytes);
    }

    pub fn resize(&mut self, rows: u16, cols: u16) {
        self.size = normalized_size(rows, cols);
        self.term.resize(self.size);
    }

    /// Terminal capability replies generated by the parser (for example DSR
    /// and device-attribute queries). The PTY owner must write these bytes
    /// back to the child process.
    pub fn take_replies(&self) -> Vec<Vec<u8>> {
        self.replies
            .drain()
            .into_iter()
            .map(String::into_bytes)
            .collect()
    }

    /// Whether the child has requested DECCKM/application cursor keys.
    pub fn application_cursor_keys(&self) -> bool {
        self.term
            .mode()
            .contains(alacritty_terminal::term::TermMode::APP_CURSOR)
    }

    /// Whether pasted text must be wrapped in the bracketed-paste protocol.
    pub fn bracketed_paste(&self) -> bool {
        self.term
            .mode()
            .contains(alacritty_terminal::term::TermMode::BRACKETED_PASTE)
    }

    /// Return the application's active mouse-reporting protocol, if any.
    /// A wheel gesture should not be sent as mouse input when an application
    /// has not opted into mouse reporting; callers can then provide a normal
    /// terminal-navigation fallback instead.
    pub fn mouse_protocol(&self) -> Option<MouseProtocol> {
        let mode = self.term.mode();
        if !mode.intersects(alacritty_terminal::term::TermMode::MOUSE_MODE) {
            return None;
        }
        if mode.contains(alacritty_terminal::term::TermMode::SGR_MOUSE) {
            Some(MouseProtocol::Sgr)
        } else {
            Some(MouseProtocol::X10)
        }
    }

    /// Move the locally rendered viewport through terminal scrollback.
    /// Returns true only when the viewport actually moved.
    pub fn scroll_viewport(&mut self, lines: i32) -> bool {
        let before = self.term.grid().display_offset();
        self.term.scroll_display(Scroll::Delta(lines));
        self.term.grid().display_offset() != before
    }

    /// Return to the live bottom of the terminal before forwarding keyboard
    /// input to the PTY, matching ordinary terminal behavior.
    pub fn scroll_viewport_to_bottom(&mut self) {
        self.term.scroll_display(Scroll::Bottom);
    }

    pub fn snapshot(&self) -> Snapshot {
        let content = self.term.renderable_content();
        let cursor = if content.display_offset == 0 {
            let cursor = content.cursor;
            let row = cursor.point.line.0;
            let column = cursor.point.column.0;
            if row >= 0 && row < self.size.rows as i32 && column < self.size.columns {
                map_cursor_shape(cursor.shape).map(|shape| TerminalCursor {
                    row: row as u16,
                    column: column as u16,
                    shape,
                })
            } else {
                None
            }
        } else {
            None
        };
        let cells: Vec<Vec<Cell>> = self
            .term
            .grid()
            .display_iter()
            .collect::<Vec<_>>()
            .chunks(self.size.columns)
            .map(|row| {
                row.iter()
                    .map(|cell| Cell {
                        text: if cell.c == '\0' {
                            " ".to_owned()
                        } else {
                            cell.c.to_string()
                        },
                        wide_continuation: cell.flags.contains(Flags::WIDE_CHAR_SPACER),
                        bold: cell.flags.contains(Flags::BOLD),
                        italic: cell.flags.contains(Flags::ITALIC),
                        underline: cell.flags.intersects(Flags::ALL_UNDERLINES),
                        inverse: cell.flags.contains(Flags::INVERSE),
                        foreground: map_color(cell.fg),
                        background: map_color(cell.bg),
                    })
                    .collect()
            })
            .collect();
        let output = cells
            .iter()
            .map(|row| {
                row.iter()
                    .map(|cell| cell.text.as_str())
                    .collect::<String>()
            })
            .collect::<Vec<_>>()
            .join("\n");
        Snapshot {
            rows: self.size.rows as u16,
            cols: self.size.columns as u16,
            output,
            cells,
            cursor,
        }
    }
}

fn map_cursor_shape(shape: AlacrittyCursorShape) -> Option<CursorShape> {
    match shape {
        AlacrittyCursorShape::Block => Some(CursorShape::Block),
        AlacrittyCursorShape::Underline => Some(CursorShape::Underline),
        AlacrittyCursorShape::Beam => Some(CursorShape::Beam),
        AlacrittyCursorShape::HollowBlock => Some(CursorShape::HollowBlock),
        AlacrittyCursorShape::Hidden => None,
    }
}

fn map_color(color: alacritty_terminal::vte::ansi::Color) -> CellColor {
    use alacritty_terminal::vte::ansi::{Color, NamedColor};
    match color {
        Color::Spec(rgb) => CellColor::Rgb {
            r: rgb.r,
            g: rgb.g,
            b: rgb.b,
        },
        Color::Indexed(index) => CellColor::Indexed(index),
        Color::Named(NamedColor::Foreground | NamedColor::BrightForeground) => {
            CellColor::DefaultForeground
        }
        Color::Named(NamedColor::Background) => CellColor::DefaultBackground,
        Color::Named(named) => CellColor::Named(named as u16),
    }
}

#[derive(Clone, Default)]
struct ReplySink(Arc<Mutex<Vec<String>>>);

impl EventListener for ReplySink {
    fn send_event(&self, event: Event) {
        if let Event::PtyWrite(reply) = event {
            self.0.lock().unwrap().push(reply);
        }
    }
}

impl ReplySink {
    fn drain(&self) -> Vec<String> {
        std::mem::take(&mut *self.0.lock().unwrap())
    }
}

fn normalized_size(rows: u16, cols: u16) -> Size {
    Size {
        rows: usize::from(rows.max(1)),
        columns: usize::from(cols.max(1)),
    }
}

#[cfg(test)]
mod tests {
    use super::Terminal;

    fn rendered(terminal: &Terminal) -> String {
        terminal.snapshot().output
    }

    #[test]
    fn preserves_cursor_position_and_text_attributes() {
        let mut terminal = Terminal::new(3, 16);
        terminal.process(b"alpha\r\nbeta\x1b[2;8H\x1b[1;4;7mOK\x1b[0m");
        let snapshot = terminal.snapshot();
        assert!(snapshot.output.contains("beta   OK"));
        let styled = &snapshot.cells[1][7];
        assert_eq!(styled.text, "O");
        assert!(styled.bold && styled.underline && styled.inverse);
    }

    #[test]
    fn restores_primary_screen_after_alternate_screen() {
        let mut terminal = Terminal::new(3, 16);
        terminal.process(b"primary\x1b[?1049hALT\x1b[?1049l");
        assert!(rendered(&terminal).contains("primary"));
        assert!(!rendered(&terminal).contains("ALT"));
    }

    #[test]
    fn marks_wide_character_continuations() {
        let mut terminal = Terminal::new(2, 8);
        terminal.process("A界B".as_bytes());
        let snapshot = terminal.snapshot();
        assert_eq!(snapshot.cells[0][1].text, "界");
        assert!(snapshot.cells[0][2].wide_continuation);
        assert_eq!(snapshot.cells[0][3].text, "B");
    }

    #[test]
    fn exposes_terminal_capability_replies() {
        let mut terminal = Terminal::new(2, 8);
        terminal.process(b"\x1b[c");
        assert!(!terminal.take_replies().is_empty());
    }

    #[test]
    fn retains_truecolor_cells() {
        let mut terminal = Terminal::new(2, 8);
        terminal.process(b"\x1b[38;2;12;34;56mX");
        assert_eq!(
            terminal.snapshot().cells[0][0].foreground,
            super::CellColor::Rgb {
                r: 12,
                g: 34,
                b: 56
            }
        );
    }

    #[test]
    fn retains_standard_bright_dim_and_indexed_colors() {
        let mut terminal = Terminal::new(2, 8);
        terminal.process(b"\x1b[31mR\x1b[91mB\x1b[2;34mD\x1b[38;5;123mI");
        let cells = &terminal.snapshot().cells[0];

        assert_eq!(cells[0].foreground, super::CellColor::Named(1));
        assert_eq!(cells[1].foreground, super::CellColor::Named(9));
        assert_eq!(cells[2].foreground, super::CellColor::Named(4));
        assert_eq!(cells[3].foreground, super::CellColor::Indexed(123));
    }

    #[test]
    fn exposes_requested_input_modes() {
        let mut terminal = Terminal::new(2, 8);
        terminal.process(b"\x1b[?1h\x1b[?2004h");
        assert!(terminal.application_cursor_keys());
        assert!(terminal.bracketed_paste());
        terminal.process(b"\x1b[?1l\x1b[?2004l");
        assert!(!terminal.application_cursor_keys());
        assert!(!terminal.bracketed_paste());
    }

    #[test]
    fn exposes_requested_mouse_protocol() {
        let mut terminal = Terminal::new(2, 8);
        assert_eq!(terminal.mouse_protocol(), None);
        terminal.process(b"\x1b[?1000h");
        assert_eq!(terminal.mouse_protocol(), Some(super::MouseProtocol::X10));
        terminal.process(b"\x1b[?1006h");
        assert_eq!(terminal.mouse_protocol(), Some(super::MouseProtocol::Sgr));
        terminal.process(b"\x1b[?1000l");
        assert_eq!(terminal.mouse_protocol(), None);
    }

    #[test]
    fn scrolls_the_local_viewport_through_history() {
        let mut terminal = Terminal::new(2, 8);
        terminal.process(b"one\r\ntwo\r\nthree");
        assert!(terminal.scroll_viewport(1));
        assert!(terminal.snapshot().output.contains("one"));
        terminal.scroll_viewport_to_bottom();
        assert!(terminal.snapshot().output.contains("three"));
    }

    #[test]
    fn includes_a_live_cursor_but_hides_it_in_scrollback_or_when_requested() {
        let mut terminal = Terminal::new(2, 8);
        terminal.process(b"abc");
        let cursor = terminal.snapshot().cursor.expect("live cursor");
        assert_eq!((cursor.row, cursor.column), (0, 3));
        terminal.process(b"\r\ndef\r\nghi");
        assert!(terminal.scroll_viewport(1));
        assert_eq!(terminal.snapshot().cursor, None);
        terminal.scroll_viewport_to_bottom();
        terminal.process(b"\x1b[?25l");
        assert_eq!(terminal.snapshot().cursor, None);
    }
}
